services:
  api:
    build: .
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; uvicorn app.api:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=clr_via_admin
      - POSTGRES_PASSWORD=clr_via_admin
      - POSTGRES_DB=clr_via
volumes:
  postgres_data: