services:
  api:
    build: .
    command: python -m uvicorn app.api:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=clrvia
      - POSTGRES_PORT=5432
      - POSTGRES_DB=clrvia
      - POSTGRES_SERVER=db
  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=clrvia
      - POSTGRES_DB=clrvia
      - POSTGRES_SERVER=db
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
volumes:
  postgres_data: